export const words = [
    // Zone 1: pronouns
    { id: 'pill-1', text: 'Je', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-2', text: 'Tu', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-3', text: 'Il', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-4', text: 'Elle', origin: 'pronom', tags: ['personal', 'emphasis'] },
    { id: 'pill-5', text: 'Nous', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-6', text: 'Vous', origin: 'pronom', tags: ['personal', 'emphasis'] },
    { id: 'pill-7', text: 'Ils', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-8', text: 'Elles', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-9', text: 'Moi', origin: 'pronom', tags: ['emphasis'] },
    { id: 'pill-10', text: 'Toi', origin: 'pronom', tags: ['emphasis'] },
    { id: 'pill-11', text: 'Lui', origin: 'pronom', tags: ['emphasis'] },
    { id: 'pill-12', text: 'Me', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-13', text: 'Te', origin: 'pronom', tags: ['personal'] },
    { id: 'pill-14', text: 'Se', origin: 'pronom', tags: ['reflexive'] }, 
    { id: 'pill-108', text: 'T\'', origin: 'pronom', tags: ['personal'] },
    // Zone 2: definite and indefinite determiners
    { id: 'pill-15', text: 'Le', origin: 'déterminant', tags: ['definite'] },
    { id: 'pill-16', text: 'La', origin: 'déterminant', tags: ['definite'] },
    { id: 'pill-17', text: 'Les', origin: 'déterminant', tags: ['definite'] },
    { id: 'pill-18', text: 'Un', origin: 'déterminant', tags: ['indefinite'] },
    { id: 'pill-19', text: 'Une', origin: 'déterminant', tags: ['indefinite'] },
    { id: 'pill-20', text: 'Des', origin: 'déterminant', tags: ['indefinite'] },
    { id: 'pill-21', text: 'Mon', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-22', text: 'Ma', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-23', text: 'Mes', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-24', text: 'Ton', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-25', text: 'Ta', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-26', text: 'Tes', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-27', text: 'Son', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-28', text: 'Sa', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-29', text: 'Ses', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-30', text: 'Notre', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-31', text: 'Nos', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-32', text: 'Votre', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-33', text: 'Vos', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-34', text: 'Leur', origin: 'déterminant', tags: ['possessive'] },
    { id: 'pill-35', text: 'Leurs', origin: 'déterminant', tags: ['possessive'] },
  
    // Zone 3: verbs    
    { id: 'pill-36', text: 'Manger', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-37', text: 'Parler', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-38', text: 'Finir', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-39', text: 'Être', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-40', text: 'Avoir', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-41', text: 'Aller', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-42', text: 'Faire', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-43', text: 'Être', origin: 'verbe', tags: ['infinitive', 'auxiliar'] },
    { id: 'pill-44', text: 'Avoir', origin: 'verbe', tags: ['infinitive', 'auxiliar'] },
    { id: 'pill-45', text: 'Mangé', origin: 'verbe', tags: ['passe_composse'] },
    { id: 'pill-46', text: 'Parlé', origin: 'verbe', tags: ['passe_composse'] },
    { id: 'pill-47', text: 'Suis', origin: 'verbe', tags: ['indicative'] },
    { id: 'pill-48', text: 'Allé', origin: 'verbe', tags: ['passe_composse'] },
    { id: 'pill-49', text: 'Regarder', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-50', text: 'Choisir', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-51', text: 'Aime', origin: 'verbe', tags: ['infinitive'] },
    { id: 'pill-52', text: 'Voyager', origin: 'verbe', tags: ['infinitive'] },
    
    // Zone 4: adverbs
    { id: 'pill-53', text: 'Rapidement', origin: 'adverbe', tags: ['manner'] },
    { id: 'pill-54', text: 'Lentement', origin: 'adverbe', tags: ['manner'] },
    { id: 'pill-55', text: 'Hier', origin: 'adverbe', tags: ['time'] },
    { id: 'pill-56', text: 'Aujourd\'hui', origin: 'adverbe', tags: ['time'] },
    { id: 'pill-57', text: 'Demain', origin: 'adverbe', tags: ['time'] },
    { id: 'pill-58', text: 'Souvent', origin: 'adverbe', tags: ['frequency'] },
    { id: 'pill-59', text: 'Jamais', origin: 'adverbe', tags: ['frequency'] },
    { id: 'pill-60', text: 'Soudainement', origin: 'adverbe', tags: ['manner'] },
    { id: 'pill-61', text: 'Toujours', origin: 'adverbe', tags: ['frequency'] },
    { id: 'pill-62', text: 'Récemment', origin: 'adverbe', tags: ['time'] },
    { id: 'pill-63', text: 'Partout', origin: 'adverbe', tags: ['place'] },
  
    // Zone 5: adjectives
    { id: 'pill-64', text: 'Grand', origin: 'adjectif', tags: ['size'] },
    { id: 'pill-65', text: 'Petit', origin: 'adjectif', tags: ['size'] },
    { id: 'pill-66', text: 'Beau', origin: 'adjectif', tags: ['appearance'] },
    { id: 'pill-67', text: 'Joli', origin: 'adjectif', tags: ['appearance'] },
    { id: 'pill-68', text: 'Intelligent', origin: 'adjectif', tags: ['intelligence'] },
    { id: 'pill-69', text: 'Difficile', origin: 'adjectif', tags: ['difficulty'] },
    { id: 'pill-70', text: 'Facile', origin: 'adjectif', tags: ['difficulty'] },
    { id: 'pill-71', text: 'Gentil', origin: 'adjectif', tags: ['kindness'] },
    { id: 'pill-72', text: 'Heureux', origin: 'adjectif', tags: ['emotion'] },
    { id: 'pill-73', text: 'Triste', origin: 'adjectif', tags: ['emotion'] },
    { id: 'pill-74', text: 'Nouveau', origin: 'adjectif', tags: ['newness'] },
  
    // Zone 6: prepositions
    { id: 'pill-75', text: 'À', origin: 'préposition', tags: ['place'] },
    { id: 'pill-76', text: 'De', origin: 'préposition', tags: ['place'] },
    { id: 'pill-77', text: 'Avec', origin: 'préposition', tags: ['inclusion'] },
    { id: 'pill-78', text: 'Pour', origin: 'préposition', tags: ['purpose'] },
    { id: 'pill-79', text: 'Sur', origin: 'préposition', tags: ['place'] },
    { id: 'pill-80', text: 'Entre', origin: 'préposition', tags: ['place'] },
    { id: 'pill-81', text: 'Devant', origin: 'préposition', tags: ['place'] },
    { id: 'pill-82', text: 'Derrière', origin: 'préposition', tags: ['place'] },
    { id: 'pill-83', text: 'Avant', origin: 'préposition', tags: ['time'] },
    { id: 'pill-84', text: 'Après', origin: 'préposition', tags: ['time'] },
    { id: 'pill-110', text: 'En', origin: 'préposition', tags: ['place'] },
    { id: 'pill-111', text: 'Chez', origin: 'préposition', tags: ['place'] },
    { id: 'pill-112', text: 'Dans', origin: 'préposition', tags: ['place'] },
  
    // Zone 7: conjunctions
    { id: 'pill-85', text: 'Et', origin: 'conjonction', tags: ['addition'] },
    { id: 'pill-86', text: 'Mais', origin: 'conjonction', tags: ['opposition'] },
    { id: 'pill-87', text: 'Ou', origin: 'conjonction', tags: ['alternative'] },
    { id: 'pill-88', text: 'Parce que', origin: 'conjonction', tags: ['cause'] },
    { id: 'pill-89', text: 'Quand', origin: 'conjonction', tags: ['time'] },
    { id: 'pill-90', text: 'Si', origin: 'conjonction', tags: ['condition'] },
    { id: 'pill-91', text: 'Alors', origin: 'conjonction', tags: ['consequence'] },
    { id: 'pill-92', text: 'Bien que', origin: 'conjonction', tags: ['concession'] },
  
    // Zone 8: common and proper commonNouns
    { id: 'pill-93', text: 'Chat', origin: 'nom', tags: ['common', 'animal'] },
    { id: 'pill-94', text: 'Chien', origin: 'nom', tags: ['common', 'animal'] },
    { id: 'pill-95', text: 'Maison', origin: 'nom', tags: ['common', 'place'] },
    { id: 'pill-96', text: 'Voiture', origin: 'nom', tags: ['common', 'object'] },
    { id: 'pill-97', text: 'Livre', origin: 'nom', tags: ['common', 'object'] },
    { id: 'pill-98', text: 'Fleur', origin: 'nom', tags: ['common', 'object'] },
    { id: 'pill-99', text: 'Santiago', origin: 'nom', tags: ['proper'] },
    { id: 'pill-100', text: 'Paris', origin: 'nom', tags: ['proper', 'place'] },
    { id: 'pill-101', text: 'École', origin: 'nom', tags: ['common', 'place'] },
    { id: 'pill-102', text: 'Téléphone', origin: 'nom', tags: ['common', 'object'] },
    { id: 'pill-103', text: 'Fête', origin: 'nom', tags: ['common', 'event'] },
    { id: 'pill-109', text: 'Amour', origin: 'nom', tags: ['common', 'emotion'] },

    // Zone 9: exclamation marks, question marks, and periods
    { id: 'pill-104', text: '!', origin: 'ponctuation', tags: [] },
    { id: 'pill-105', text: '?', origin: 'ponctuation', tags: [] },
    { id: 'pill-106', text: '.', origin: 'ponctuation', tags: [] },
    { id: 'pill-107', text: ',', origin: 'ponctuation', tags: [] },
];  